### ISSUE TITLE
Slug issue

### ISSUE THREAD

**Issue by AJE-2015** [tehplayground/support#12]
Last week, everything was fine, but today, it's no more possible to use slug hashs to save a content.
To produce the issue:

1. Open a new browser tab on https://www.tehplayground.com/
2. Type som code, for example: <?php print "Hello, world!";
3. Press Save and Run
4. The code is run in the right panel and au slug is created and displayed in the adress bar
5. Copy the url, for example https://www.tehplayground.com/sYUQ2MQ7Fs4sAYxS
6. Open a new tab and paste the url
7. Validate

You get this error:
404 Not Found
    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: sYUQ2MQ7Fs4sAYxS
    RequestId: A2NFSC54K5QHBQ5Z
    HostId: GXcWgKz5KmiDYwJfZ7WX4Gi/BzMuz8mULX8cq7zRrwza4stB85nkymzUZv4A7+hyixzylT+L/O8=

By the way, all of the olders urls/slugs are ineffective. Everything is lost.
Might be a database server down?

**Comment by silvervest** [comment]
Hey! Apologies about that and it should now be resolved.
Performed a big infrastructure migration last week and missed some rewrite rules :)

Cheers!
