### ISSUE TITLE
Are server time settings wrong?

### ISSUE THREAD

**Issue by oxk4r01** [tehplayground/support#4]
When I issue time(), in the Theplayground, the result is one hour and 11 minutes before my local time. Why those 11 minutes? I think there is something wrong with the server time config... could it be?

**Comment by silvervest** [comment]
Hey! Thanks for logging this.

You're 100% correct, it appears that I blocked outbound ntp in a very lazy attempt to mitigate NTP-based DDoS amplification attacks, but that caused the ntp daemon to not be able to keep time drift in check.
I've sorted this out now, and time should be and stay accurate within the second.

Thanks again!
