### ISSUE TITLE
Missing escaping

### ISSUE THREAD

**Issue by Logifire** [tehplayground/support#5]
Should html escape the output to the right, see image:

![image](https://user-images.githubusercontent.com/16954276/52497916-9fc59580-2bd7-11e9-86d5-c88c9bfa0158.png)

**Comment by silvervest** [comment]
Hello, and thanks for the report.

Have fixed escaping of HTML content when `Wrap in <pre>` output is enabled (default), as seen at https://tehplayground.com/koQlFSASTShWRUKk
The tags will continue to render normally when `Wrap in <pre>` is disabled.

Cheers,
Nick
