### ISSUE TITLE
Support for PHP 7.4 and 8.0

### ISSUE THREAD

**Issue by boan-jfm** [tehplayground/support#7]
ATM. the latest version seems to be 7.2 - will there be support for later versions?

**Comment by silvervest** [comment]
Hey there,

Apologies for the delay, I don't have a lot of time to maintain this project any longer.
However, I've updated the containers and deployed 8.0.3, 7.4.16, and 7.3.27 as the currently accessible containers.

Enjoy!

Cheers,
Nick
